steps:
  - label: "Build + Test (nightly rust)"
    commands:
      - ".ci/build-test"
    agents: &build-agent
      production: "true"
      platform: "linux"
    env: &build-docker-nightly
      DOCKER_IMAGE: "gcr.io/opensourcecoin/radicle-avatar-build-nightly@sha256:3e2d6ce8675087b99e2b36330a6d1b2d68a66b274cdba006c0caef397907e8cb"
      DOCKER_FILE: .docker/nightly/Dockerfile

  - label: "Build + Test (stable rust)"
    commands:
      - ".ci/build-test"
    agents: &build-agent
      production: "true"
      platform: "linux"
    env: &build-docker-stable
      DOCKER_IMAGE: "gcr.io/opensourcecoin/radicle-avatar-build-stable@sha256:ecba622a4db1bee4a5c074defbb24e003fd5f81c7e5a83b900a4aee87c76caea"
      DOCKER_FILE: .docker/stable/Dockerfile

  - label: "Clippy Yeah Yeah Clippy Shlippy Yeah"
    commands:
      - ".ci/clippy"
    agents: *build-agent
    env: *build-docker-nightly

  - label: "Deny"
    commands:
      - ".ci/advisory"
    agents: *build-agent
    env: *build-docker-nightly

  - label: "Docs"
    commands:
      - ".ci/docs"
    agents: *build-agent
    env: *build-docker-nightly
